//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSExportaFichero {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ecp-test.alpiq.com:4431/ECP.WebServices-NoAuth/AtosService.svc")]
        public string WSExportaFichero_ServicioFacturadorPre_AtosService {
            get {
                return ((string)(this["WSExportaFichero_ServicioFacturadorPre_AtosService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ecp-test.alpiq.com/ECP.WebServices-NoAuth/AtosService.svc")]
        public string WSExportaFichero_ServicioFacturadorNoAuthSecuredPre_AtosService {
            get {
                return ((string)(this["WSExportaFichero_ServicioFacturadorNoAuthSecuredPre_AtosService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ecp-test.alpiq.com/ECP.WebServices/AtosService.svc")]
        public string WSExportaFichero_ServicioFacturadorAuthSecuredPre_AtosService {
            get {
                return ((string)(this["WSExportaFichero_ServicioFacturadorAuthSecuredPre_AtosService"]));
            }
        }
    }
}
