//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSExportaFichero.SrvFacturadorAuthSecuredPro {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="arg0", Namespace="")]
    [System.SerializableAttribute()]
    public partial class arg0 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string comercializadoraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipoField, value) != true)) {
                    this.tipoField = value;
                    this.RaisePropertyChanged("tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string xml {
            get {
                return this.xmlField;
            }
            set {
                if ((object.ReferenceEquals(this.xmlField, value) != true)) {
                    this.xmlField = value;
                    this.RaisePropertyChanged("xml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string comercializadora {
            get {
                return this.comercializadoraField;
            }
            set {
                if ((object.ReferenceEquals(this.comercializadoraField, value) != true)) {
                    this.comercializadoraField = value;
                    this.RaisePropertyChanged("comercializadora");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://send.ws.atos.com/", ConfigurationName="SrvFacturadorAuthSecuredPro.AtosService")]
    public interface AtosService {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://send.ws.atos.com/)
        [System.ServiceModel.OperationContractAttribute(Action="processSend", ReplyAction="")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SrvFacturadorAuthSecuredPro.AtosResponse processSend(SrvFacturadorAuthSecuredPro.AtosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="processSend", ReplyAction="")]
        System.Threading.Tasks.Task<SrvFacturadorAuthSecuredPro.AtosResponse> processSendAsync(SrvFacturadorAuthSecuredPro.AtosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processSend", WrapperNamespace="http://send.ws.atos.com/", IsWrapped=true)]
    public partial class AtosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SrvFacturadorAuthSecuredPro.arg0 arg0;
        
        public AtosRequest() {
        }
        
        public AtosRequest(SrvFacturadorAuthSecuredPro.arg0 arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="processSendResponse", WrapperNamespace="http://send.ws.atos.com/", IsWrapped=true)]
    public partial class AtosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AtosResponse() {
        }
        
        public AtosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AtosServiceChannel : SrvFacturadorAuthSecuredPro.AtosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AtosServiceClient : System.ServiceModel.ClientBase<SrvFacturadorAuthSecuredPro.AtosService>, SrvFacturadorAuthSecuredPro.AtosService {
        
        public AtosServiceClient() {
        }
        
        public AtosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AtosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SrvFacturadorAuthSecuredPro.AtosResponse SrvFacturadorAuthSecuredPro.AtosService.processSend(SrvFacturadorAuthSecuredPro.AtosRequest request) {
            return base.Channel.processSend(request);
        }
        
        public string processSend(SrvFacturadorAuthSecuredPro.arg0 arg0) {
            SrvFacturadorAuthSecuredPro.AtosRequest inValue = new SrvFacturadorAuthSecuredPro.AtosRequest();
            inValue.arg0 = arg0;
            SrvFacturadorAuthSecuredPro.AtosResponse retVal = ((SrvFacturadorAuthSecuredPro.AtosService)(this)).processSend(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SrvFacturadorAuthSecuredPro.AtosResponse> SrvFacturadorAuthSecuredPro.AtosService.processSendAsync(SrvFacturadorAuthSecuredPro.AtosRequest request) {
            return base.Channel.processSendAsync(request);
        }
        
        public System.Threading.Tasks.Task<SrvFacturadorAuthSecuredPro.AtosResponse> processSendAsync(SrvFacturadorAuthSecuredPro.arg0 arg0) {
            SrvFacturadorAuthSecuredPro.AtosRequest inValue = new SrvFacturadorAuthSecuredPro.AtosRequest();
            inValue.arg0 = arg0;
            return ((SrvFacturadorAuthSecuredPro.AtosService)(this)).processSendAsync(inValue);
        }
    }
}
